# Generated by Django 4.2.2 on 2023-06-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dht11",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.IntegerField()),
                ("humidity", models.IntegerField()),
                ("datetime", models.DateTimeField()),
            ],
            options={
                "db_table": "dht11",
                "managed": False,
            },
        ),
    ]
